#!/bin/bash

echo "=== Hatırlatıcı Çalıştırma Rehberi ==="
echo ""
echo "1. Twilio Console'a gidin: https://console.twilio.com/"
echo "2. Account SID ve Auth Token'ı kopyalayın"
echo "3. .env dosyasını güncelleyin:"
echo "   nano .env"
echo ""
echo "4. Scripti çalıştırmak için:"
echo "   cd /root/hatirlatici"
echo "   source twilio_env/bin/activate"
echo "   python send_message.py"
echo ""
echo "=== Mevcut Durum ==="
echo "✅ Python Virtual Environment: HAZIR"
echo "✅ Twilio Package: YÜKLÜ"
echo "✅ Environment Variables: AYARLI"
echo "⚠️  Twilio Credentials: DOĞRULANMASI GEREKİYOR"
echo ""
echo "Lütfen Twilio Console'dan doğru bilgileri alıp .env dosyasını güncelleyin."
