#!/bin/bash

echo "📱 TWİLİO WHATSAPP SANDBOX AYAR REHBERİ"
echo "========================================"
echo ""
echo "🎯 YAPMANIZ GEREKENLER:"
echo ""
echo "1. Twilio Console'a gidin:"
echo "   https://console.twilio.com/us1/develop/sms/try-it-out/whatsapp-learn"
echo ""
echo "2. Sayfada göreceğiniz bilgiler:"
echo "   📞 Sandbox Numarası: +1 415 523 8886 (veya benzer)"
echo "   🔑 Join Kodu: 'join XXXX-XXXX' (iki kelime)"
echo ""
echo "3. Yeni telefon (+905346184108) ile:"
echo "   - WhatsApp'ı açın"
echo "   - +1 415 523 8886 numarasına mesaj gönderin"
echo "   - Mesaj: 'join XXXX-XXXX' (Console'da gördüğünüz kodu)"
echo ""  
echo "4. Başarılı olursa göreceğiniz mesaj:"
echo "   'You are now connected to the Twilio Sandbox...'"
echo ""
echo "5. Test edin:"
echo "   ./manage.sh test"
echo ""
echo "🚨 ÖNEMLİ: Her yeni numara için bu işlem tekrarlanmalı!"
echo ""
echo "📞 Mevcut Ayarlar:"
cat .env | grep -E "TWILIO_WHATSAPP_NUMBER|RECIPIENT_WHATSAPP_NUMBER"
echo ""
echo "✅ Sandbox ayarından sonra sistem otomatik çalışacak!"
